### ISSUE TITLE
What’s The point od this sample app if cross platform not supported

### ISSUE THREAD

**Issue by MikePapinski** [DevExpress-Examples/maui-stocks-mini#1]
What's the point of this sample app if it cannot target MacCatalyst and/or Windows. The whole point of .net Maui is to be able to develop across desktop and mobiles together. For iOS/Android we have xamarin, for macOS/windows we have avalonia. I would love to use this example for my trade app however I need to be able to target both desktop and mobile envs.

**Comment by dennis-garavsky** [comment]
@MikePapinski: Microsoft has positioned .NET MAUI as the evolution of Xamarin as well (its end of life is at the end of 2022-2023 due to .NET MAUI release shift to Q2 2022). Based on the initial feedback, many customers want to build MAUI-based COMPANION mobile apps to help supplement existing desktop offerings (for instance, WinForms or WPF apps).

NOTE: building desktop apps with the MAUI platform is serious/expensive undertaking. Have you and your team considered the consequences associated with a transition away from WinForms/WPF to MAUI?

If so, and you are prepared to write your .NET MAUI apps from scratch (for Windows/Mac desktop and mobile devices), we would appreciate it if you tell us more about your future application requirements:

**1. Will the Android and iOS apps offer fewer functions or have the same capabilities as Windows/Mac desktop apps?
2. Do you expect your .NET MAUI apps on mobile platforms (iOS/Android) to look & behave quite differently from apps on a desktop platform (Windows and macOS)?
3. If so, how do you expect to customize UI/UX for each device form-factor in your cross-platform .NET MAUI apps (from a developer point of view)?**

I am asking because many customers made a few most critical modules available from mobile apps (for instance, one navigation item to input new orders or contacts). Or desktop apps require a full-featured grid, while mobile apps are fine with a simple list, which is a totally different UI control (code sharing across platforms becomes a question).

As most in the community, we are excited about the capabilities that .NET MAUI offers for cross-platform UI development. Many questions arise when we talk about the details of this cross-platform UI, though. We will finalize our plans for desktop support in our MAUI controls in 2022. Your answers to the questions above and also to our survey will surely help: https://community.devexpress.com/blogs/news/archive/2021/12/20/winforms-wpf-winui-survey-decide-whats-coming-next-to-your-desktop-app.aspx.

**Comment by MikePapinski** [comment]
thank you for your feedback.

1. The same functions, I want to port avalonia desktop app to maui.
2. Not really they should have exactly the same.
3. The same way as responsive bootstrap components are resizing when you change the frame resolution.
